server:
    port: 8778

debug: true

spring:
    cloud:
        zookeeper:
            connectString: 127.0.0.1:2181
            enabled: false
    sleuth:
        enabled: false

swagger:
    basePackage: com.test1.test1.controller
    title: ctg-test1-test1 RESTful APIs
    description: ctg-test1-test1 RESTful API
    version: 1.0.0-SNAPSHOT
    openApi:
        group: OpenApi
        basePackage: com.test1.test1.controller
        title: actg-test1-test1 Open APIs
        description: ctg-test1-test1 Open API
        version: 1.0.0-SNAPSHOT
